### ISSUE TITLE
Semana 1

### ISSUE THREAD

**Issue by carlosecp** [Pablo1107/algo3-tp2#2]
# Resumen
Durante la primera reunión lo que buscamos fue identificar en qué cosas debemos trabajar esta primera semana y cómo las vamos a ir trabajando en equipo.

## Tareas Semana 1

Vamos a enfocarnos principalmente en cumplir con los tres casos de uso propuestos por el enunciado del TP.
* "Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos."
* "Un auto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos."
* "Una 4x4 atraviesa la ciudad y se encuentra con un Pozo. No es penalizada."

Para esto identificamos las posibles tareas en las que podemos dividir esto. Vamos a tener que arrancar con las implementación y pruebas de:

* Jugador
  * Esta entidad va a tener su propio vehiculo dentro.
  * También va a llevar control de su propio puntaje (porque puede ser que su vehículo sea cambiado).
  * Esta entidad es la que vamos a mover como tal. Osea, la posicion que nos importa en el tablero de juego, es realmente la posición del jugador, no la del vehículo, por el mismo tema de que el vehículo puede cambiar.
* Vehículo
  * Vamos a tener que implementar los tres tipos de vehículo para satisfacer los casos de uso propuestos.
  * También vamos a tener que implementar las diferentes penalizaciones para cada tipo de vehículo. Por el momento solo vamos a tener un obstáculo que va a ser el Pozo, pero para los casos de uso adicionales podemos agregar más obstáculos.
* Juego
  * Debemos verificar que al movernos X movimientos, tomemos en cuenta el tema de las penalizaciones y todo eso y al final del juego, tengamos un puntaje correcto. No me refiero solo a que la penalización de un obstáculo en un vehículo en un momento dado es correcta, sino que también debemos ir desarrollando el modelo básico del juego, sin interfaz ni nada de eso, solo que cuando lleguemos al fin, pues lleguemos con X movimientos (esto lo planteabamos en la entrega 0). 

Notas adicionales:
  * Por el momento no nos vamos a enfocar en el tema de los dirección del movimiento. No nos interesa probar todavía moverse en una dirección u otra, simplemente nos interesa el tema de movernos, pasar por obstáculos y tener una penalización. 

## Workflow Propuesto
La idea del workflow que queremos probar es que utilizamos la pestaña "Projects" de este repositorio en Github para ver en que están trabajando los demás, así venimos nosotros, vemos si hay una tarea pendiente, y la seleccionamos para encargarnos de eso nosotros. Cuando creamos una nueva tarea en esa sección, podemos crear un issue como este donde vamos a ir comentando, lo demás vamos a ir lanzando sugerencias sobre en lo que están trabajando los demás en esos issues.

También si por ejemplo, yo estoy trabajando en algo todavía, pero se me ocurre que es buena idea implementar, que se yo, un nuevo objeto Mapa o algo así, puedo crear la tarea, explicar un poco mi idea en un issue, y así cuando otro compañero termine sus tarea, si busca otra puede agarrar la que creé. En los issues de cada feature, podemos ir mandando los diagramas de clases por ejemplo para ver si a los demás integrantes les parecen o si tienen sugerencias.

Idealmente vamos a hacer un resumen de qué metas plantearnos cada semana.

**Comment by carlosecp** [comment]
Bueno hice algunos cambios en el diagrama de secuencia que habia propuesto.
![image](https://user-images.githubusercontent.com/47466248/171952785-bb695a8c-3e0d-4fc3-afa7-1352e843c3ca.png)
Hay cosas que vamos a tener que cambiar. Por ejemplo en este diagrama lo que pretendia hacer es que los obstaculos sean quienes guarden las diferentes penalizaciones que cada obstaculo puede tener para los diferentes tipos de vehiculo, pero quiza esto tenga que cambiar para la proxima semana cuando agreguemos los otros elementos en el mapa. Por ahora voy a plantear los casos de uso actuales e ir avanzando en mi propuesta del codigo asi a ver que les parece.

**Comment by Pablo1107** [comment]
El cuarto caso de uso esta en #7
