### ISSUE TITLE
Metodo estaDentroDelMapa, delegar en mapa

### ISSUE THREAD

**Issue by Pablo1107** [Pablo1107/algo3-tp2#24]
Cambiarlo a `Posicion.estaDentroDeLimite(int limiteX, int limiteY);`

Y en Mapa se llama como:
```
posicion.estaDentroDeLimite(this.limiteX, this.limiteY)
```

**Comment by carlosecp** [comment]
Hay un inconveniento con esto y es que no veo como deshacerme completamente de los getters sin dejar las firmas de `Jugador` un poco cargadas tambien, se explica mejor en este thread de Slack: https://programacion3fiuba.slack.com/archives/C03JP9LE6V7/p1655677372595939
